[package]
authors = ["scrubjay55"]
name = "dynamiclibrary"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies.windows-sys]
version = "0.29.0"
features = ["Win32_Foundation", "Win32_System_Console"]
